// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5mTz-138BsqU81BRYeiy95jqDRCsub2I',
    appId: '1:218952490030:web:c131edc9335a0d271b93bf',
    messagingSenderId: '218952490030',
    projectId: 'sosialmediatwiter',
    authDomain: 'sosialmediatwiter.firebaseapp.com',
    storageBucket: 'sosialmediatwiter.firebasestorage.app',
    measurementId: 'G-70D9MR1S7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP0MRaat31UA88JFpu6esW2Gews-qy220',
    appId: '1:218952490030:android:40eb751d0c80c53a1b93bf',
    messagingSenderId: '218952490030',
    projectId: 'sosialmediatwiter',
    storageBucket: 'sosialmediatwiter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNqnm4nakTJsCS48bF1k_sl_tPjx3Xv8k',
    appId: '1:218952490030:ios:74d48e5f3b1f8ce41b93bf',
    messagingSenderId: '218952490030',
    projectId: 'sosialmediatwiter',
    storageBucket: 'sosialmediatwiter.firebasestorage.app',
    iosBundleId: 'com.example.uasTwitterMediasosial',
  );
}
